FROM pytorch/pytorch:1.12.0-cuda11.3-cudnn8-devel

# Remove any third-party apt sources to avoid issues with expiring keys.
RUN rm -f /etc/apt/sources.list.d/*.list

# Install some basic utilities
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    sudo \
    git \
    bzip2 \
    libx11-6 \
 && rm -rf /var/lib/apt/lists/*

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y
RUN  apt-get clean && \
  rm -rf /var/lib/apt
  
ENV TZ=Japan/Tokyo
RUN sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime

# Create a working directory
RUN mkdir /app
WORKDIR /app

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user \
 && chown -R user:user /app
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER user

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN mkdir $HOME/.cache $HOME/.config \
 && chmod -R 777 $HOME

# Set up the Conda environment
ENV CONDA_AUTO_UPDATE_CONDA=false \
    PATH=$HOME/miniconda/bin:$PATH
COPY environment.yml /app/environment.yml
RUN curl -sLo ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p ~/miniconda \
 && rm ~/miniconda.sh \
 && conda env update -n base -f /app/environment.yml \
 && rm /app/environment.yml \
 && conda clean -ya

# Install system libraries required by OpenCV.
RUN sudo apt-get update \
    && sudo apt-get install -y libgl1-mesa-glx libgtk2.0-0 libsm6 libxext6 \
    && sudo rm -rf /var/lib/apt/lists/*

# Install OpenMMLab.
RUN pip install openmim
RUN mim install mmcv-full==1.5.0 \
    && mim install mmdet \
    && mim install mmpose \
    && mim install mmaction2

# Install requirements from PyPI.
# RUN pip install -r requirements.txt
RUN pip install pytorch_lightning \
    fvcore \
    timm \
    scikit-learn \
    scipy

# Set the default command to python3
CMD ["python3"]
