trainer:
  default_root_dir: exp/pull-up-compare
  max_epochs: 30
  early_stopping: false
  enable_checkpointing: null
  num_nodes: 1
  devices: 1
  gpus: 1
  log_gpu_memory: true
  enable_progress_bar: true
  overfit_batches: 0.0
  check_val_every_n_epoch: 1
  min_epochs: 1
  accelerator: auto
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  benchmark: false
  deterministic: true
  auto_lr_find: false
  prepare_data_per_node: null
  patience: 10
optimizer:
  method: AdamW
  lr: 0.00005
  momentum: 0.9
  weight_decay: 0.0001
  eps: 0.00000001
lr_scheduler:
  policy: StepLR
  gamma: 0.1
  step: 10
model:
  num_class: 2
  backbone_model: convnext_base
data:
  dataset_type: ImageDataset
  data_root: data/pull-up-relabeled
  batch_size: 8
  train:
    anno: data/pull-up-relabeled/train.txt
    data_prefix: null
  val:
    anno: data/pull-up-relabeled/val.txt
    data_prefix: null
  test:
    anno: data/pull-up-relabeled/test.txt
    data_prefix: null
  num_workers: 4
  transform: null
  target_transform: null
log:
  output_dir: exp/pull-up-compare
  name: pull-up-relabel-convnext_base-lr_5e-5
  log_every_n_steps: 20
  tensorboard:
    enable: true
  wandb:
    enable: false
    offline: false
    project: pull-up
seed: 0
train: true
checkpoint: null
