trainer:
  default_root_dir: exp/repcount-12-tdn # where to save logs and checkpoints
  max_epochs: 50
  enable_checkpointing: true
  num_nodes: 1
  devices: auto
  gpus: auto
  log_gpu_memory: null
  enable_progress_bar: true
  overfit_batches: 10
  check_val_every_n_epoch: 1
  min_epochs: 1
  accelerator: auto
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  benchmark: false
  deterministic: true
  auto_lr_find: false
  auto_scale_batch_size: null
  prepare_data_per_node: null
  fast_dev_run: false
optimizer:
  method: SGD
  lr: 0.005
  momentum: 0.9
  weight_decay: 5.0e-4
  eps: 1.0e-8
lr_scheduler:
  policy: StepLR
  gamma: 0.1
  step: 8

model:
  model_type: TDN
  num_class: 12
  num_segments: 8
  num_frames: 5
  base_model: resnet50
  consensus_type: avg
  dropout: 0.5
  partial_bn: false
  fc_lr5: false
  checkpoint: checkpoints/finetune/tdn_sthv2_r50_8x1x1.pth

data:
  dataset_type: TDNDataset
  data_root: /home/user/data
  num_segments: 8
  num_frames: 5
  filename_tmpl: 'img_{:05}.jpg'
  anno_col: 4
  batch_size: 4
  num_workers: 8
  train:
    anno: /home/user/data/Binary/all-train.txt
    data_prefix: null
    transform:
      person_crop: false
  val:
    anno: /home/user/data/Binary/all-val.txt
    data_prefix: null
    transform:
      person_crop: false
  test:
    anno: /home/user/data/Binary/all-test.txt
    data_prefix: null
    transform:
      person_crop: false

log:
  output_dir: null # os.path.join(trainer.default_root_dir, timestamp)
  log_every_n_steps: 20
  csv:
    enable: true
  tensorboard:
    enable: true
  wandb:
    enable: false
    offline: false
    project: repcount-12-tdn
    name: repcount-12-tdn

callbacks:
  modelcheckpoint:
    save_top_k: 1
    save_weights_only: false
    monitor: val/acc
    mode: max
    dirpath: null # if None, defaults to log.output_dir
  early_stopping:
    enable: false
    patience: 10

seed: 0
train: true
timestamp: null # Will be initialized in python file
